// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for TestSubscriptionFunction
 */
export interface TestSubscriptionFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/lambdas/test-subsciption/test-subscription.
 */
export class TestSubscriptionFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: TestSubscriptionFunctionProps) {
    super(scope, id, {
      description: 'src/lambdas/test-subsciption/test-subscription.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs20.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/lambdas/test-subsciption/test-subscription.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}